### PR TITLE
docs: improves the installation instructions

### PR DESCRIPTION
**Pull request by imasdekar**
- Changes the flow of some installation steps which I found to be confusing.
- Also adds missing instructions to install some plugins before enabling them.

Signed-off by: Ishan Masdekar <imasdekar@disroot.org>

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @imasdekar! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by imasdekar** [comment]
I have signed the CLA

**Comment by mphilbrick211** [comment]
Hi @imasdekar! Thanks for this contribution, and for submitting your CLA form. I will look into getting checks enabled on this pull request.

**Comment by imasdekar** [comment]
I have fixed the commit lint for which the checks failed

**Comment by imasdekar** [comment]
@openedx/cla-problems I have already submitted the signed cla days ago. Am I still missing something?

**Comment by mphilbrick211** [comment]
Hi @imasdekar! Our legal team sent you an email just now with some next steps.

**Comment by imasdekar** [comment]
@mphilbrick211  I have already clarified this twice on email with Eden Huthmacher (got the replies on it as well) about my personal email. But I do not know why it is being flagged again. Hence explaining it here in comments for the 3rd time.

My email address imasdekar@disroot.org is my personal/individual email address and not associated to any organization. It is provided by [disroot.org](https://disroot.org/en) which is an independent mail provider just like gmail or any other and not an organization where I work.

Also 2nd reason for declining my cla was my missing mailing address. However in the cla form [here](https://tcril.tfaforms.net/f/individual-cla) i can see that mailing address is a mandatory field(* marked). So I do not think that I proceeded without providing my mailing address. 

Let me know if you still want me to re-submit it.

**Comment by mphilbrick211** [comment]
> @mphilbrick211 I have already clarified this twice on email with Eden Huthmacher (got the replies on it as well) about my personal email. But I do not know why it is being flagged again. Hence explaining it again here in comments.
> 
> My email address [imasdekar@disroot.org](mailto:imasdekar@disroot.org) is my personal/individual email address and not associated to any organization. It is provided by [disroot.org](https://disroot.org/en) which is an independent mail provider just like gmail or any other and not an organization where I work.
> 
> Also 2nd reason for declining my cla was my missing mailing address. However in the cla form [here](https://tcril.tfaforms.net/f/individual-cla) i can see that mailing address is a mandatory field(* marked). So I do not think that I proceeded without providing my mailing address.
> 
> Let me know if you still want me to re-submit it.

Hi @imasdekar - I'm checking on this for you!

**Comment by imasdekar** [comment]
@mphilbrick211 The [frontend-app-library-authoring repo](https://github.com/openedx-unsupported/frontend-app-library-authoring) is archived. Hence this PR is not required any more.

**Comment by openedx-webhooks** [comment]
@imasdekar Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-tutor-plugins&entry.867055334=https://github.com/openedx/openedx-tutor-plugins/pull/23&entry.1484655318=https://github.com/imasdekar&entry.752974735=2024-04-21+15:50&entry.1917517419=2024-08-02+10:09&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
