### PR TITLE
feat!: tutor-contrib-library-authoring-mfe

### PR DESCRIPTION
**Pull request by kdmccormick**
The Library Authoring MFE has been subsumed into the Course Authoring MFE.

https://github.com/openedx-unsupported/frontend-app-library-authoring/issues/439

### CODE REVIEW

**Review by bradenmacdonald — APPROVED** [review]
I'm assuming we can still install this plugin from an old git hash if we need to. We recently had to use it during development, since the new UI isn't fully built out yet.

But I'm happy to get rid of the plugin now.

**Comment by kdmccormick** [comment]
Hm, I've never tried installing from an old git hash. I don't mind leaving the plugin here for a couple more months until the Course Authoring MFE has been built out enough.

**Comment by kdmccormick** [comment]
I added this PR to https://github.com/openedx/frontend-app-course-authoring/issues/1115

**Comment by bradenmacdonald** [comment]
@kdmccormick This is ready to merge. I just merged https://github.com/openedx/frontend-app-authoring/pull/1327

**Pull request merged**
